### ISSUE TITLE
깃허브 로그인 연동

### ISSUE THREAD

**Issue by junu0516** [junu0516/GithubIssueManager#4]
## 💡 Goal
- 전반적인 MVVM에 맞는 구조를 (뼈대만이라도) 구현
- Alamofire을 사용하는 네트워크 계층 구현 후 GET 요청에 대한 응답 정상적으로 오는지 확인
    
## 💡Tasks
- [x] 로그인 화면 구현
- [x] 로그인 뷰모델 구현
- [x] 네트워크, Repository 계층 구현
- [x] 깃허브 로그인 연동, Access Token 응답받기

**Comment by junu0516** [comment]
### 💡 인증을 위한 API Key 값을 어떻게 관리할 것인가?
> 아래와 같은 대안을 놓고 고민해봤음
- 서버(혹은 Firebase)로부터 키값을 응답받아서, API를 요청
- plist 파일을 만들어서 키를 관리하고, 해당 파일에 대해서는 git이 추적하지 못하도록 설정
- 키값을 암호화시켜서 swift 파일로 관리?

결과적으로 2번째 대안을 선택했음
- 혼자 작업하는 것이기 때문에 plist 파일을 만들어 관리하는 것이 이후 작업에 편리
- github에 커밋내역을 푸시해도 plist 파일의 변경내역은 추적하지 않기 때문에 타인이 키값을 알 수 없음
- 깃이 추적하지 않을 뿐이지 plist 파일의 원형 자체는 푸시되기 때문에, 타인은 적어도 해당 파일에 키 정보가 있어야 함을 인지할 수 있음
